services:
  calendar-app:
    build: .
    container_name: calendar-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"